services:
  - type: web
    name: lotef-api
    runtime: node
    rootDir: server
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    nodeVersion: "20"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
